
- name: 'Abrir puerto https'
  firewalld:
    service: https
    permanent: true
    state: enabled
  tags: app

- name: 'Abrir puerto 30000'
  firewalld:
    port: 30000/tcp
    permanent: true
    state: enabled

- name: 'Reinicio firewall'
  systemd:
    name: firewalld
    state: reloaded
  tags: app

- name: 'Crear directorio git'
  file:
    path: ./unir-cp2-app
    state: directory
    mode: 0755
  tags: app

- name: 'Instalar git'
  yum:
    name: git
    state: present
    update_cache: yes
  tags: app

- name: 'Clonar repositorio git'
  git:
    repo: https://github.com/ReBedc/unir-cp2-app.git
    dest: ./unir-cp2-app
    clone: yes
    update: yes
    version: master
  tags: app

- name: 'Crear namespace'
  command: kubectl create namespace jenkins-nm
  run_once: true
  register: command_result
  failed_when: "'Updating' in command_result.stdout"
  tags: app

- name: 'Crear services'
  command: kubectl apply -f ./unir-cp2-app/jenkins-services.yaml --namespace jenkins-nm
  tags: app

- name: 'Crear PV'
  command: kubectl create -f ./unir-cp2-app/jenkins-pv.yaml --namespace jenkins-nm
  tags: app

- name: 'Crear service NFS'
  command: kubectl apply -f ./unir-cp2-app/nfs-service.yaml --namespace jenkins-nm
  tags: app

- name: 'Crear deployment'
  command: kubectl create -f ./unir-cp2-app/jenkins-deployment.yaml --namespace jenkins-nm
  tags: app

