---
# tasks file for role_worker

# Puertos 30000 y 50000 para jenkins
# Puertos 2049 y 111 para NFS
- name: 'Añadir puertos firewalld'
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 8285/udp
    - 8472/udp
    - 30000-32767/tcp
    - 10250/tcp
    - 30000/tcp
    - 50000/tcp
    - 2049/tcp
    - 111/udp
  notify: Reinicio firewall
  tags: worker
