# Playbook que instala las ultimas versiones de software disponibles
# y posteriormente reinicia el nodo gestionado
# $ ansible-playbook -i inventory playbook.yaml -K
---
- name: 'Actualizacion de sistema operativo e instalaci贸n de rpms'
  hosts: all
  remote_user: azureuser
  become: true
  vars_files:
    - vars.yaml
  tasks:
    - name: 'Ejecucion de tareas comunes'
      include_role:
        name: role_common
      tags: common
    
    - name: 'Configuraci贸n de NFS'
      include_role:
        name: role_nfs
      when: inventory_hostname in groups['nfs']
      tags: nfs

    - name: 'Instalar kubernetes y dependencias'
      include_role:
        name: role_kubernetes
      when: inventory_hostname in groups['kubernetes']
      tags: kubernetes

    - name: 'Configuraci贸n de kubernetes en master'
      include_role:
        name: role_master
      when: inventory_hostname in groups['master']
      tags: master

    - name: 'Configuraci贸n de kubernetes en worker'
      include_role:
        name: role_worker
      when: inventory_hostname in groups['worker']
      tags: worker

 

