---



- hosts: master
  remote_user: azureuser
  become: true
  gather_facts: false

  tasks:

  - name: Creamos un nuevo token para el Cluster-Join
    command: kubeadm token create --print-join-command
    register: join_command
  
  - debug:
      var: join_command
  
  - name: set join command
    set_fact:
      join_command: "{{ join_command.stdout_lines[0] }}"

  - debug:
      var: join_command
  - debug:
      msg: " Prueba {{ hostvars['20.0.60.186'].join_command }}"

- hosts: worker
  remote_user: azureuser
  become: true
  tasks:
  - debug:
      var: join_command
  - debug:
      msg: " Prueba {{ hostvars }}"
  - debug:
      msg: " Prueba {{ ansible_facts['default_ipv4']['address'] }}"

  - name: Agregamos workers al cluster
    become: yes
    shell: "{{ hostvars['20.0.60.186'].join_command }} >> node_joined.txt"
    args:
      chdir: $HOME
      creates: node_joined.txt