---
- hosts: master
  remote_user: azureuser
  become: true
  gather_facts: false
  vars_files:
    - vars.yaml
  tasks:
  - name: 'Crear un nuevo token para el join del worker'
    command: kubeadm token create --print-join-command
    register: join_command
  
  - debug:
      var: join_command
  
  - name: 'Setear variable join_command'
    set_fact:
      join_command: "{{ join_command.stdout_lines[0] }}"

  - name: 'Obtener ip master de variables'
    set_fact:
      ip_master:  "{{ ip_master }}"

  - debug:
      var: ip_master

  - debug:
      var: join_command
  - debug:
      msg: " Prueba {{ hostvars[ip_master].join_command }}"

- hosts: worker
  remote_user: azureuser
  become: true
  gather_facts: false
  tasks:
  # - name: 'Obtener ip master de variables2'
  #   set_fact:
  #     ip_master2:  "{{ ip_master }}"

  # - debug:
  #     var: ip_master2

  - debug:
      msg: " Prueba worker {{ hostvars['20.254.46.16'].join_command }}"

  # - debug:
  #     msg: " Prueba {{ ansible_facts['default_ipv4']['address'] }}"

  - name: 'Agregamos worker al cluster'
    become: yes
    shell: "{{ hostvars['20.254.46.16'].join_command }} >> node_joined_result.txt"
    args:
      chdir: $HOME
      creates: node_joined_result.txt