- name: 'Actualizacion de sistema operativo e instalación de rpms'
  hosts: master
  remote_user: azureuser
  become: true
  tasks:
 
    - name: 'Configuración de jenkins'
      include_role:
        name: role_app
      when: inventory_hostname in groups['master']
      tags: app