# Playbook que instala las ultimas versiones de software disponibles
# y posteriormente reinicia el nodo gestionado
# $ ansible-playbook -i inventory playbook.yaml -K
---
- name: 'Actualizacion de sistema operativo e instalación de rpms'
  hosts: all
  remote_user: azureuser
  become: true
  vars_files:
    - vars.yaml
  tasks:
    - name: 'Ejecucion de tareas comunes'
      include_role:
        name: role_common
      tags: role_common